variable "env" {}
variable "component" {}
variable "instant_type" {}
variable "vpc_id" {}
variable "sg_cidr_blocks" {}
variable "bastion_cidrs" {}
variable "app_port" {}
variable "instant_capacity" {}
variable "project_name" {}
variable "vpc_zone_identifier" {}